# Zsh plugins w/ Antidote
source $(brew --prefix)/opt/antidote/share/antidote/antidote.zsh
antidote load

# Tab autocomplete
autoload -Uz compinit
compinit -u

# Shell prompt w/ Starship
eval "$(starship init zsh)"

# fzf
eval "$(fzf --zsh)"

# Aliases for modern CLI tools
alias cat="bat"
alias ls="eza"
alias grep="rg"
