# Yash's .zshrc

# Zsh plugins w/ Antidote
source $(brew --prefix)/opt/antidote/share/antidote/antidote.zsh
antidote load

# Tab autocomplete
autoload -Uz compinit
compinit -u

# Shell prompt w/ Starship
eval "$(starship init zsh)"

# fzf
eval "$(fzf --zsh)"

# Aliases for modern CLI tools
alias cat="bat"
alias ls="eza"
alias cd="z"

# Claude Code
export PATH="$HOME/.local/bin:$PATH"

# Cargo installed binaries
export PATH="$HOME/.cargo/bin:$PATH"

# Dotdrop profile
export DOTDROP_PROFILE=macbook

# Enable zoxide (must go last)
eval "$(zoxide init zsh)"

