config:
  dotpath: dotfiles

actions:
  post:
    antidote-bundle: 'source $(brew --prefix)/opt/antidote/share/antidote/antidote.zsh && mkdir -p ${{HOME}}/.local/share/zsh && antidote bundle < ${{HOME}}/.config/zsh/plugins.txt > ${{HOME}}/.local/share/zsh/plugins.zsh'

dotfiles:
  f_zshenv_stub:
    dst: ~/.zshenv
    src: shells/zsh/zshenv-stub
  f_zshrc:
    dst: ~/.config/zsh/.zshrc
    src: shells/zsh/zshrc
  f_zshenv:
    dst: ~/.config/zsh/.zshenv
    src: shells/zsh/zshenv
  f_zprofile:
    dst: ~/.config/zsh/.zprofile
    src: shells/zsh/zprofile
  f_zsh_plugins:
    dst: ~/.config/zsh/plugins.txt
    src: shells/zsh/zsh_plugins.txt
    actions:
      - antidote-bundle
  d_helix:
    dst: ~/.config/helix
    src: editors/helix
  f_tmux:
    dst: ~/.config/tmux/tmux.conf
    src: tmux/tmux.conf
  f_starship:
    dst: ~/.config/starship.toml
    src: starship.toml
  f_eza:
    dst: ~/.config/eza/theme.yml
    src: eza.yml
  f_iterm2:
    dst: ~/.config/iterm2/themes/catppuccin-mocha.itermcolors
    src: iterm2.itermcolors
  d_bat:
    dst: ~/.config/bat
    src: bat
  f_yazi:
    dst: ~/.config/yazi/theme.toml
    src: yazi.toml
  d_git:
    dst: ~/.config/git
    src: git
  f_wget:
    dst: ~/.config/wget/wgetrc
    src: wget/wgetrc
  f_vim:
    dst: ~/.config/vim/vimrc
    src: editors/vim/vimrc

profiles:
  macbook:
    dotfiles:
      - ALL
