" Persistent history, marks, and registers
set viminfofile=$XDG_STATE_HOME/vim/viminfo

" Backup, swap, and undo files
set backupdir=$XDG_STATE_HOME/vim/backup//
set directory=$XDG_STATE_HOME/vim/swap//
set undodir=$XDG_STATE_HOME/vim/undo//
set undofile
